name: Plugin asset/readme update
on:
    push:
        branches:
            - main
jobs:
    master:
        name: Push to main
        runs-on: ubuntu-latest
        steps:
            # - name: Install Act dependencies
            #   if: ${{ env.ACT }}
            #   run: |
            #     apt-get update && apt-get install composer -y && apt-get install git -y
            - uses: actions/checkout@master
            - name: Stash changes
              run: git stash
            - name: WordPress.org plugin asset/readme update
              uses: 10up/action-wordpress-plugin-asset-update@stable
              env:
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SLUG: subscription
